// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'api/core.dart';
import 'api/logger.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.9.0';

  @override
  int get rustContentHash => 429739323;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_privastead_flutter',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<Clients> crateApiCoreClientsNew({
    required String appMotionName,
    required String appLivestreamName,
    required String appFcmName,
    required String appConfigName,
    required bool firstTime,
    required String fileDir,
  });

  Future<MyMobileLogger> crateApiLoggerMyMobileLoggerNew({
    required LevelFilter level,
  });

  Future<SendToDartLogger> crateApiLoggerSendToDartLoggerNew({
    required LevelFilter level,
  });

  Stream<LogEntry> crateApiLoggerSendToDartLoggerSetStreamSink();

  Future<bool> crateApiCoreAddCamera({
    required OptionBoxClients clientsReg,
    required String cameraName,
    required String cameraIp,
    required List<int> secretVec,
    required bool standaloneCamera,
    required String wifiSsid,
    required String wifiPassword,
  });

  Stream<LogEntry> crateApiLoggerCreateLogStream();

  Future<String> crateApiDecryptFcmMessage({
    required String cameraName,
    required List<int> data,
  });

  Future<String> crateApiCoreDecryptFcmMessage({
    required OptionBoxClients clients,
    required List<int> message,
  });

  Future<String> crateApiDecryptVideo({
    required String cameraName,
    required String encFilename,
  });

  Future<String> crateApiCoreDecryptVideo({
    required OptionBoxClients clients,
    required String encryptedFilename,
  });

  Future<void> crateApiCoreDeregister({required OptionBoxClients clients});

  Future<void> crateApiDeregisterCamera({required String cameraName});

  Future<bool> crateApiFlutterAddCamera({
    required String cameraName,
    required String ip,
    required List<int> secret,
    required bool standalone,
    required String ssid,
    required String password,
  });

  Future<String> crateApiGetLivestreamGroupName({required String cameraName});

  Future<String> crateApiCoreGetLivestreamGroupName({
    required OptionBoxClients clients,
    required String cameraName,
  });

  Future<String> crateApiGetMotionGroupName({required String cameraName});

  Future<String> crateApiCoreGetMotionGroupName({
    required OptionBoxClients clients,
    required String cameraName,
  });

  Future<void> crateApiInitApp();

  Future<void> crateApiLoggerInitLogger();

  Future<bool> crateApiCoreInitialize({
    required OptionBoxClients clients,
    required String fileDir,
    required bool firstTime,
  });

  Future<bool> crateApiInitializeCamera({
    required String cameraName,
    required String fileDir,
    required bool firstTime,
  });

  Future<Uint8List> crateApiLivestreamDecrypt({
    required String cameraName,
    required List<int> data,
    required BigInt expectedChunkNumber,
  });

  Future<Uint8List> crateApiCoreLivestreamDecrypt({
    required OptionBoxClients clients,
    required List<int> encData,
    required BigInt expectedChunkNumber,
  });

  Future<bool> crateApiLivestreamUpdate({
    required String cameraName,
    required List<int> msg,
  });

  Future<void> crateApiCoreLivestreamUpdate({
    required OptionBoxClients clients,
    required List<int> updatesMsg,
  });

  Future<bool> crateApiPingProprietaryDevice({required String cameraIp});

  Future<void> crateApiLoggerRustSetUp();

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Clients;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Clients;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ClientsPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_LevelFilter;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_LevelFilter;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_LevelFilterPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_MyMobileLogger;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_MyMobileLogger;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_MyMobileLoggerPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_OptionBoxClients;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_OptionBoxClients;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_OptionBoxClientsPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_SendToDartLogger;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_SendToDartLogger;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SendToDartLoggerPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<Clients> crateApiCoreClientsNew({
    required String appMotionName,
    required String appLivestreamName,
    required String appFcmName,
    required String appConfigName,
    required bool firstTime,
    required String fileDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(appMotionName, serializer);
          sse_encode_String(appLivestreamName, serializer);
          sse_encode_String(appFcmName, serializer);
          sse_encode_String(appConfigName, serializer);
          sse_encode_bool(firstTime, serializer);
          sse_encode_String(fileDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClients,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCoreClientsNewConstMeta,
        argValues: [
          appMotionName,
          appLivestreamName,
          appFcmName,
          appConfigName,
          firstTime,
          fileDir,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreClientsNewConstMeta => const TaskConstMeta(
    debugName: "Clients_new",
    argNames: [
      "appMotionName",
      "appLivestreamName",
      "appFcmName",
      "appConfigName",
      "firstTime",
      "fileDir",
    ],
  );

  @override
  Future<MyMobileLogger> crateApiLoggerMyMobileLoggerNew({
    required LevelFilter level,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLevelFilter(
            level,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMyMobileLogger,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLoggerMyMobileLoggerNewConstMeta,
        argValues: [level],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLoggerMyMobileLoggerNewConstMeta =>
      const TaskConstMeta(debugName: "MyMobileLogger_new", argNames: ["level"]);

  @override
  Future<SendToDartLogger> crateApiLoggerSendToDartLoggerNew({
    required LevelFilter level,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLevelFilter(
            level,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSendToDartLogger,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLoggerSendToDartLoggerNewConstMeta,
        argValues: [level],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLoggerSendToDartLoggerNewConstMeta =>
      const TaskConstMeta(
        debugName: "SendToDartLogger_new",
        argNames: ["level"],
      );

  @override
  Stream<LogEntry> crateApiLoggerSendToDartLoggerSetStreamSink() {
    final streamSink = RustStreamSink<LogEntry>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_log_entry_Sse(streamSink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 4,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiLoggerSendToDartLoggerSetStreamSinkConstMeta,
          argValues: [streamSink],
          apiImpl: this,
        ),
      ),
    );
    return streamSink.stream;
  }

  TaskConstMeta get kCrateApiLoggerSendToDartLoggerSetStreamSinkConstMeta =>
      const TaskConstMeta(
        debugName: "SendToDartLogger_set_stream_sink",
        argNames: ["streamSink"],
      );

  @override
  Future<bool> crateApiCoreAddCamera({
    required OptionBoxClients clientsReg,
    required String cameraName,
    required String cameraIp,
    required List<int> secretVec,
    required bool standaloneCamera,
    required String wifiSsid,
    required String wifiPassword,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOptionBoxClients(
            clientsReg,
            serializer,
          );
          sse_encode_String(cameraName, serializer);
          sse_encode_String(cameraIp, serializer);
          sse_encode_list_prim_u_8_loose(secretVec, serializer);
          sse_encode_bool(standaloneCamera, serializer);
          sse_encode_String(wifiSsid, serializer);
          sse_encode_String(wifiPassword, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoreAddCameraConstMeta,
        argValues: [
          clientsReg,
          cameraName,
          cameraIp,
          secretVec,
          standaloneCamera,
          wifiSsid,
          wifiPassword,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreAddCameraConstMeta => const TaskConstMeta(
    debugName: "add_camera",
    argNames: [
      "clientsReg",
      "cameraName",
      "cameraIp",
      "secretVec",
      "standaloneCamera",
      "wifiSsid",
      "wifiPassword",
    ],
  );

  @override
  Stream<LogEntry> crateApiLoggerCreateLogStream() {
    final s = RustStreamSink<LogEntry>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_log_entry_Sse(s, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 6,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiLoggerCreateLogStreamConstMeta,
          argValues: [s],
          apiImpl: this,
        ),
      ),
    );
    return s.stream;
  }

  TaskConstMeta get kCrateApiLoggerCreateLogStreamConstMeta =>
      const TaskConstMeta(debugName: "create_log_stream", argNames: ["s"]);

  @override
  Future<String> crateApiDecryptFcmMessage({
    required String cameraName,
    required List<int> data,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(cameraName, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDecryptFcmMessageConstMeta,
        argValues: [cameraName, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDecryptFcmMessageConstMeta => const TaskConstMeta(
    debugName: "decrypt_fcm_message",
    argNames: ["cameraName", "data"],
  );

  @override
  Future<String> crateApiCoreDecryptFcmMessage({
    required OptionBoxClients clients,
    required List<int> message,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOptionBoxClients(
            clients,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(message, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCoreDecryptFcmMessageConstMeta,
        argValues: [clients, message],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreDecryptFcmMessageConstMeta =>
      const TaskConstMeta(
        debugName: "decrypt_fcm_message",
        argNames: ["clients", "message"],
      );

  @override
  Future<String> crateApiDecryptVideo({
    required String cameraName,
    required String encFilename,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(cameraName, serializer);
          sse_encode_String(encFilename, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDecryptVideoConstMeta,
        argValues: [cameraName, encFilename],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDecryptVideoConstMeta => const TaskConstMeta(
    debugName: "decrypt_video",
    argNames: ["cameraName", "encFilename"],
  );

  @override
  Future<String> crateApiCoreDecryptVideo({
    required OptionBoxClients clients,
    required String encryptedFilename,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOptionBoxClients(
            clients,
            serializer,
          );
          sse_encode_String(encryptedFilename, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCoreDecryptVideoConstMeta,
        argValues: [clients, encryptedFilename],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreDecryptVideoConstMeta => const TaskConstMeta(
    debugName: "decrypt_video",
    argNames: ["clients", "encryptedFilename"],
  );

  @override
  Future<void> crateApiCoreDeregister({required OptionBoxClients clients}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOptionBoxClients(
            clients,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoreDeregisterConstMeta,
        argValues: [clients],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreDeregisterConstMeta =>
      const TaskConstMeta(debugName: "deregister", argNames: ["clients"]);

  @override
  Future<void> crateApiDeregisterCamera({required String cameraName}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(cameraName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDeregisterCameraConstMeta,
        argValues: [cameraName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeregisterCameraConstMeta => const TaskConstMeta(
    debugName: "deregister_camera",
    argNames: ["cameraName"],
  );

  @override
  Future<bool> crateApiFlutterAddCamera({
    required String cameraName,
    required String ip,
    required List<int> secret,
    required bool standalone,
    required String ssid,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(cameraName, serializer);
          sse_encode_String(ip, serializer);
          sse_encode_list_prim_u_8_loose(secret, serializer);
          sse_encode_bool(standalone, serializer);
          sse_encode_String(ssid, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFlutterAddCameraConstMeta,
        argValues: [cameraName, ip, secret, standalone, ssid, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlutterAddCameraConstMeta => const TaskConstMeta(
    debugName: "flutter_add_camera",
    argNames: ["cameraName", "ip", "secret", "standalone", "ssid", "password"],
  );

  @override
  Future<String> crateApiGetLivestreamGroupName({required String cameraName}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(cameraName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetLivestreamGroupNameConstMeta,
        argValues: [cameraName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetLivestreamGroupNameConstMeta =>
      const TaskConstMeta(
        debugName: "get_livestream_group_name",
        argNames: ["cameraName"],
      );

  @override
  Future<String> crateApiCoreGetLivestreamGroupName({
    required OptionBoxClients clients,
    required String cameraName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOptionBoxClients(
            clients,
            serializer,
          );
          sse_encode_String(cameraName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCoreGetLivestreamGroupNameConstMeta,
        argValues: [clients, cameraName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreGetLivestreamGroupNameConstMeta =>
      const TaskConstMeta(
        debugName: "get_livestream_group_name",
        argNames: ["clients", "cameraName"],
      );

  @override
  Future<String> crateApiGetMotionGroupName({required String cameraName}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(cameraName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetMotionGroupNameConstMeta,
        argValues: [cameraName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetMotionGroupNameConstMeta => const TaskConstMeta(
    debugName: "get_motion_group_name",
    argNames: ["cameraName"],
  );

  @override
  Future<String> crateApiCoreGetMotionGroupName({
    required OptionBoxClients clients,
    required String cameraName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOptionBoxClients(
            clients,
            serializer,
          );
          sse_encode_String(cameraName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCoreGetMotionGroupNameConstMeta,
        argValues: [clients, cameraName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreGetMotionGroupNameConstMeta =>
      const TaskConstMeta(
        debugName: "get_motion_group_name",
        argNames: ["clients", "cameraName"],
      );

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiLoggerInitLogger() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLoggerInitLoggerConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLoggerInitLoggerConstMeta =>
      const TaskConstMeta(debugName: "init_logger", argNames: []);

  @override
  Future<bool> crateApiCoreInitialize({
    required OptionBoxClients clients,
    required String fileDir,
    required bool firstTime,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOptionBoxClients(
            clients,
            serializer,
          );
          sse_encode_String(fileDir, serializer);
          sse_encode_bool(firstTime, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCoreInitializeConstMeta,
        argValues: [clients, fileDir, firstTime],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreInitializeConstMeta => const TaskConstMeta(
    debugName: "initialize",
    argNames: ["clients", "fileDir", "firstTime"],
  );

  @override
  Future<bool> crateApiInitializeCamera({
    required String cameraName,
    required String fileDir,
    required bool firstTime,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(cameraName, serializer);
          sse_encode_String(fileDir, serializer);
          sse_encode_bool(firstTime, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitializeCameraConstMeta,
        argValues: [cameraName, fileDir, firstTime],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitializeCameraConstMeta => const TaskConstMeta(
    debugName: "initialize_camera",
    argNames: ["cameraName", "fileDir", "firstTime"],
  );

  @override
  Future<Uint8List> crateApiLivestreamDecrypt({
    required String cameraName,
    required List<int> data,
    required BigInt expectedChunkNumber,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(cameraName, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          sse_encode_u_64(expectedChunkNumber, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLivestreamDecryptConstMeta,
        argValues: [cameraName, data, expectedChunkNumber],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLivestreamDecryptConstMeta => const TaskConstMeta(
    debugName: "livestream_decrypt",
    argNames: ["cameraName", "data", "expectedChunkNumber"],
  );

  @override
  Future<Uint8List> crateApiCoreLivestreamDecrypt({
    required OptionBoxClients clients,
    required List<int> encData,
    required BigInt expectedChunkNumber,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOptionBoxClients(
            clients,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(encData, serializer);
          sse_encode_u_64(expectedChunkNumber, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCoreLivestreamDecryptConstMeta,
        argValues: [clients, encData, expectedChunkNumber],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreLivestreamDecryptConstMeta =>
      const TaskConstMeta(
        debugName: "livestream_decrypt",
        argNames: ["clients", "encData", "expectedChunkNumber"],
      );

  @override
  Future<bool> crateApiLivestreamUpdate({
    required String cameraName,
    required List<int> msg,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(cameraName, serializer);
          sse_encode_list_prim_u_8_loose(msg, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLivestreamUpdateConstMeta,
        argValues: [cameraName, msg],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLivestreamUpdateConstMeta => const TaskConstMeta(
    debugName: "livestream_update",
    argNames: ["cameraName", "msg"],
  );

  @override
  Future<void> crateApiCoreLivestreamUpdate({
    required OptionBoxClients clients,
    required List<int> updatesMsg,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOptionBoxClients(
            clients,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(updatesMsg, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCoreLivestreamUpdateConstMeta,
        argValues: [clients, updatesMsg],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreLivestreamUpdateConstMeta =>
      const TaskConstMeta(
        debugName: "livestream_update",
        argNames: ["clients", "updatesMsg"],
      );

  @override
  Future<bool> crateApiPingProprietaryDevice({required String cameraIp}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(cameraIp, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPingProprietaryDeviceConstMeta,
        argValues: [cameraIp],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPingProprietaryDeviceConstMeta =>
      const TaskConstMeta(
        debugName: "ping_proprietary_device",
        argNames: ["cameraIp"],
      );

  @override
  Future<void> crateApiLoggerRustSetUp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLoggerRustSetUpConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLoggerRustSetUpConstMeta =>
      const TaskConstMeta(debugName: "rust_set_up", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Clients =>
      wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClients;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Clients =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClients;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_LevelFilter =>
      wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLevelFilter;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_LevelFilter =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLevelFilter;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_MyMobileLogger =>
      wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMyMobileLogger;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_MyMobileLogger =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMyMobileLogger;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_OptionBoxClients =>
      wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOptionBoxClients;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_OptionBoxClients =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOptionBoxClients;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_SendToDartLogger =>
      wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSendToDartLogger;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_SendToDartLogger =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSendToDartLogger;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  Clients
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClients(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ClientsImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LevelFilter
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLevelFilter(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LevelFilterImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  MyMobileLogger
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMyMobileLogger(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MyMobileLoggerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SendToDartLogger
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSendToDartLogger(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SendToDartLoggerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  OptionBoxClients
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOptionBoxClients(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return OptionBoxClientsImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Clients
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClients(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ClientsImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LevelFilter
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLevelFilter(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LevelFilterImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  MyMobileLogger
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMyMobileLogger(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MyMobileLoggerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  OptionBoxClients
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOptionBoxClients(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return OptionBoxClientsImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SendToDartLogger
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSendToDartLogger(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SendToDartLoggerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<LogEntry> dco_decode_StreamSink_log_entry_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  LogEntry dco_decode_log_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return LogEntry(
      timeMillis: dco_decode_i_64(arr[0]),
      level: dco_decode_i_32(arr[1]),
      tag: dco_decode_String(arr[2]),
      msg: dco_decode_String(arr[3]),
    );
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  Clients
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClients(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ClientsImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  LevelFilter
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLevelFilter(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LevelFilterImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  MyMobileLogger
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMyMobileLogger(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MyMobileLoggerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SendToDartLogger
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSendToDartLogger(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SendToDartLoggerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  OptionBoxClients
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOptionBoxClients(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return OptionBoxClientsImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Clients
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClients(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ClientsImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  LevelFilter
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLevelFilter(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LevelFilterImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  MyMobileLogger
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMyMobileLogger(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MyMobileLoggerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  OptionBoxClients
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOptionBoxClients(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return OptionBoxClientsImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SendToDartLogger
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSendToDartLogger(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SendToDartLoggerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<LogEntry> sse_decode_StreamSink_log_entry_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  LogEntry sse_decode_log_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_timeMillis = sse_decode_i_64(deserializer);
    var var_level = sse_decode_i_32(deserializer);
    var var_tag = sse_decode_String(deserializer);
    var var_msg = sse_decode_String(deserializer);
    return LogEntry(
      timeMillis: var_timeMillis,
      level: var_level,
      tag: var_tag,
      msg: var_msg,
    );
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClients(
    Clients self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ClientsImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLevelFilter(
    LevelFilter self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as LevelFilterImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMyMobileLogger(
    MyMobileLogger self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as MyMobileLoggerImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSendToDartLogger(
    SendToDartLogger self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SendToDartLoggerImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOptionBoxClients(
    OptionBoxClients self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as OptionBoxClientsImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClients(
    Clients self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ClientsImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLevelFilter(
    LevelFilter self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as LevelFilterImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMyMobileLogger(
    MyMobileLogger self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as MyMobileLoggerImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOptionBoxClients(
    OptionBoxClients self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as OptionBoxClientsImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSendToDartLogger(
    SendToDartLogger self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SendToDartLoggerImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_log_entry_Sse(
    RustStreamSink<LogEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_log_entry,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_log_entry(LogEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.timeMillis, serializer);
    sse_encode_i_32(self.level, serializer);
    sse_encode_String(self.tag, serializer);
    sse_encode_String(self.msg, serializer);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class ClientsImpl extends RustOpaque implements Clients {
  // Not to be used by end users
  ClientsImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ClientsImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Clients,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Clients,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_ClientsPtr,
  );
}

@sealed
class LevelFilterImpl extends RustOpaque implements LevelFilter {
  // Not to be used by end users
  LevelFilterImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  LevelFilterImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_LevelFilter,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_LevelFilter,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_LevelFilterPtr,
  );
}

@sealed
class MyMobileLoggerImpl extends RustOpaque implements MyMobileLogger {
  // Not to be used by end users
  MyMobileLoggerImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  MyMobileLoggerImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_MyMobileLogger,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_MyMobileLogger,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_MyMobileLoggerPtr,
  );
}

@sealed
class OptionBoxClientsImpl extends RustOpaque implements OptionBoxClients {
  // Not to be used by end users
  OptionBoxClientsImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  OptionBoxClientsImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_OptionBoxClients,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_OptionBoxClients,
    rustArcDecrementStrongCountPtr:
        RustLib
            .instance
            .api
            .rust_arc_decrement_strong_count_OptionBoxClientsPtr,
  );
}

@sealed
class SendToDartLoggerImpl extends RustOpaque implements SendToDartLogger {
  // Not to be used by end users
  SendToDartLoggerImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  SendToDartLoggerImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_SendToDartLogger,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_SendToDartLogger,
    rustArcDecrementStrongCountPtr:
        RustLib
            .instance
            .api
            .rust_arc_decrement_strong_count_SendToDartLoggerPtr,
  );
}
