// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Blocking lock
Future<bool> acquireLock({required String path}) =>
    RustLib.instance.api.crateApiLockManagerAcquireLock(path: path);

/// Non-blocking lock
Future<bool> tryAcquireLock({required String path}) =>
    RustLib.instance.api.crateApiLockManagerTryAcquireLock(path: path);

/// Release a previously acquired lock
Future<void> releaseLock({required String path}) =>
    RustLib.instance.api.crateApiLockManagerReleaseLock(path: path);

/// Check if the current process holds the lock
Future<bool> isLockHeld({required String path}) =>
    RustLib.instance.api.crateApiLockManagerIsLockHeld(path: path);
