// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `current_log_trace`, `record_to_entry`, `set_log_trace`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `LogTraceGuard`, `SEND_TO_DART_LOGGER_STREAM_SINK`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `as_log`, `config`, `deref`, `drop`, `enabled`, `flush`, `initialize`, `level`, `log`

Stream<LogEntry> createLogStream() =>
    RustLib.instance.api.crateApiLoggerCreateLogStream();

Future<void> rustSetUp() => RustLib.instance.api.crateApiLoggerRustSetUp();

Future<void> rustShutdown() =>
    RustLib.instance.api.crateApiLoggerRustShutdown();

Future<void> initLogger() => RustLib.instance.api.crateApiLoggerInitLogger();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SendToDartLogger>>
abstract class SendToDartLogger implements RustOpaqueInterface {
  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<SendToDartLogger> newInstance({required LevelFilter level}) =>
      RustLib.instance.api.crateApiLoggerSendToDartLoggerNew(level: level);

  static Stream<LogEntry> setStreamSink() =>
      RustLib.instance.api.crateApiLoggerSendToDartLoggerSetStreamSink();
}

class LogEntry {
  final PlatformInt64 timeMillis;
  final int level;
  final String tag;
  final String msg;
  final String? traceId;

  const LogEntry({
    required this.timeMillis,
    required this.level,
    required this.tag,
    required this.msg,
    this.traceId,
  });

  @override
  int get hashCode =>
      timeMillis.hashCode ^
      level.hashCode ^
      tag.hashCode ^
      msg.hashCode ^
      traceId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LogEntry &&
          runtimeType == other.runtimeType &&
          timeMillis == other.timeMillis &&
          level == other.level &&
          tag == other.tag &&
          msg == other.msg &&
          traceId == other.traceId;
}
